namespace: "fortinet"
name: "fortianalyzer"
version: "1.8.1"
readme: "README.md"
authors:
    - "Xinwei Du (@dux-fortinet)"
    - "Link Zheng (@chillancezen)"
    - "Xue Jie (@JieX19)"
    - "Hongbin Lu (@fgtdev-hblu)"
    - "Frank Shen (@frankshen01)"
description: "The FortiAnalyzer Ansible Collection."
license:
    - "GPL-3.0-or-later"
tags:
    - fortinet
    - fortianalyzer
    - ansible
    - networking
    - security
    - firewall
dependencies: { "ansible.netcommon": "*" }
repository: "https://github.com/fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection"
documentation: "https://ansible-galaxy-fortianalyzer-docs.readthedocs.io/en/latest"
homepage: "https://fortinet.com"
issues: "https://github.com/fortinet-ansible-dev/ansible-galaxy-fortianalyzer-collection/issues"
build_ignore:
    - ".github"
